name: artic
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - artic-porechop==0.3.2pre
  - artic-tools==0.3.0
  - bcftools=1.10.2
  - biopython=1.76
  - bwa=0.7.17
  - clint=0.5.1
  - htslib=1.10.2
  - minimap2=2.17
  - multiqc
  - muscle=3.8
  - nanopolish=0.13.2
  - nomkl
  - pandas
  - pip
  - pysam=0.16.0.1
  - pytest
  - python=3.6
  - pyvcf=0.6.8
  - samtools=1.10
  - tqdm
  - whatshap
  - parasail-python
  - pip:
      - medaka==1.2.3
